# Generated by Django 4.1.3 on 2022-11-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_review_user_remove_ticket_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
